### ISSUE TITLE
A User can Add a new product

### ISSUE THREAD

**Issue by racheldaniel** [raving-remoras/Bangazon-React#23]
- [x] A user has an affordance from the product list to add a new product
- [x] On the new product form, a user has the option to select from pre-existing customers (sellers) and product types
- [ ]  Once the user selects a customer or product type, they have the affordance to edit that entity (see edit form for customer #39 and product type #27 )
- [ ]  A user can also add a new customer or  product type from the add order page (see add form for customer #38 and product type #26 )
- [x]  The user has the option to save-- which routes back to product list

**Comment by kellymorin** [comment]
Completed, team decided to not allow for adding or editing other entities from the edit form.
