### ISSUE TITLE
A User can Edit a Product

### ISSUE THREAD

**Issue by racheldaniel** [raving-remoras/Bangazon-React#24]
- [x] When the user clicks on an individual product, they will be taken to a detail page, which is structured as a pre-populated edit form
- [x]  On the edit product form, a user has the option to select from pre-existing customers (sellers) and product types
- [ ]  Once the user selects a customer or product type, they have the affordance to edit that entity (edit forms from customer #39 and product type #27)
- [ ]  A user can also add a new customer or  product type from the add order page (add forms from customer #38 and product type #26)
- [x]  The user has the option to save -- which routes back to product list

**Comment by kellymorin** [comment]
Completed, team decided to not allow for adding or editing other entities from the edit form.
