### ISSUE TITLE
A User Can Add a New Order

### ISSUE THREAD

**Issue by racheldaniel** [raving-remoras/Bangazon-React#35]
- [x]  On the order view page, a user has an affordance to add a new order
- [x]  On the new order form, a user has the option to select from pre-existing customers and payment types
- [ ] Once the user selects a customer or payment type, they have the affordance to edit that entity (edit forms from tickets #39 and #30)
- [ ] A user can also add a new payment type and/or customer from the add order page (edit froms from tickets #38 and #29)
- [x] The user has the option to "save"-- which routes back to order list

**Comment by kellymorin** [comment]
Completed, team decided to not allow for adding or editing other entities from the add form.
